
replicas: 1

proxy:
  image:
    repo: nginxinc/nginx-unprivileged
    tag: latest
    pullPolicy: IfNotPresent
  containerName: "proxy"

  port: 8081

  resources:
    requests:
      memory: 1Gi
      cpu: "250m"
    limits:
      memory: 1Gi
      cpu: "500m"

app:
  image:
    repo: alpacked/test-task
    tag: latest
    pullPolicy: IfNotPresent
  containerName: "app"

  port: 8080

  resources:
    requests:
      memory: 1Gi
      cpu: "400m"
    limits:
      memory: 1Gi
      cpu: "600m"


service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

storage:
  accessMode: ReadWriteOnce
  capacity: 1G
  mountPoint: /app/uploads
  persistMetadata: true