apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-nginx-config"
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels" . | indent 4 }}
data:
  default.conf: |
    upstream fs-app {
        server 127.0.0.1:{{ .Values.app.port }};
    }

    server {
        listen {{ .Values.proxy.port }};

        client_max_body_size 25M;

        location /ping {
            limit_except GET {
                deny all;
            }

            return 200 'pong';
        }

        location /health {
            limit_except GET {
                deny all;
            }

            proxy_pass       http://fs-app/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /upload {
            limit_except POST {
                deny all;
            }

            proxy_pass       http://fs-app/upload;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location ~ /uploads/(.*) {
           limit_except GET {
                deny all;
            }

            alias           {{ .Values.storage.mountPoint }}/$1;

            add_header       Content-disposition "attachment";
        }
    }