apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-account"
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-binding"
  labels: {{- include "common.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-account"
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: "{{ .Release.Name }}-role"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-role"
  labels: {{- include "common.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmap", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "watch", "list"]
